server:
  port: 8090
  tomcat:

    connection-timeout: 2s
    keep-alive-timeout: 15s

    ## re-write the default value of max-threads to reduce resource consumption
    threads:
      max: 50
      min-spare: 5